import React, { createContext, useContext, useMemo, useState, useCallback, useEffect } from 'react';
import { teExtras, hiExtras } from './locales/langExtras.js';

const LanguageContext = createContext();

/** Every pill id in LanguagePillBar — explicit dict so lookups never miss. */
export const SUPPORTED_LANG_CODES = [
  'en',
  'te',
  'hi',
  'ta',
  'kn',
  'ml',
  'vi',
  'id',
  'th',
  'zh',
  'bn',
  'es',
  'fr',
  'ar',
  'pt',
  'ru',
  'ja',
  'ko',
  'de',
  'it',
  'tr'
];

// Base English dictionary
const enDict = {
  'nav.products': 'Our Products',
  'nav.about': 'Our Story',
  'nav.results': 'Success Stories',
  'nav.rnd': 'Innovation Lab',
  'nav.updates': 'Latest Updates',
  'nav.contact': 'Contact Us',
  'nav.lang': 'Language',
  
  'hero.badge': 'Growing Together',
  'hero.title1': 'Growing Together,',
  'hero.title2': 'Thriving Together.',
  'hero.subtitle': 'FARMERS WHO FEED THE FUTURE, THANK YOU',
  'hero.btn1': 'Discover Our Products',
  'hero.btn2': 'Watch Success Story',
  'hero.stat.growth': 'Growth Rate',
  'hero.stat.survival': 'Survival Rate',
  
  'about.tag': 'Our Story',
  'about.title': 'The Confier Genesis',
  'about.desc': 'At Confier International, we are steadfast in our commitment to the health, vitality, and sustainability of aquatic life. We deliver premium, eco-friendly shrimp feed supplements and advanced probiotics engineered to enhance growth metrics and promote highly sustainable aquaculture practices.',
  'about.pillar1.title': 'The Confier Advantage',
  'about.pillar1.text': 'Where Science Meets Sustainability. Our proprietary feed supplements are meticulously crafted by leading aquaculture experts and biochemists utilizing only the finest natural ingredients.',
  'about.pillar2.title': 'Our North Star',
  'about.pillar2.text': 'Our mission is to unequivocally redefine the future of global aquaculture through cutting-edge, eco-conscious feed supplements, empowering shrimp farmers globally.',
  'about.pillar3.title': 'Tailored Solutions',
  'about.pillar3.text': 'By remaining closely attuned to the evolving challenges and needs of shrimp farming communities on the ground, we continuously develop next-generation bespoke supplements.',
  
  'prod.tag': 'Our Products',
  'prod.title': 'Premium Feed Supplements',
  'prod.desc': 'Scientific formulations designed to enhance growth, survival, and pond health.',
  'prod.details': 'View Details',
  'prod.interact': 'Tap to Interact 3D',
  'prod.price.contact': 'Contact for pricing',
  'prod.modal.rotate3d': 'Drag to rotate the 3D model',
  'prod.modal.verifiedBenefits': 'Verified benefits',
  'prod.modal.composition': 'Composition',
  'prod.modal.instructions': 'Instructions for use',
  'prod.modal.dosage': 'Dosage',
  'prod.modal.netContent': 'Net content',
  'prod.modal.caaNo': 'CAA no.',
  'prod.modal.bulkNote': 'Need bulk pricing? Translated manuals available.',
  'prod.addToCart': 'Add to cart',
  'prod.wishlist': 'Wishlist',
  'prod.saved': 'Saved',
  'prod.modal.close': 'Close',
  
  'rnd.tag': 'Innovation Lab',
  'rnd.title': 'Research & Development',
  'rnd.desc': 'Engineering the future of aquaculture through uncompromising scientific inquiry and biotechnological innovation. Innovations in shrimp feed supplements are the primary drivers of healthier growth.',
  'rnd.pillar1.title': 'Expertise & Knowledge',
  'rnd.pillar1.desc': 'Decades of industry expertise combined with avant-garde scientific innovation to deliver premium-quality shrimp feed supplements.',
  'rnd.pillar2.title': 'Quality & Excellence',
  'rnd.pillar2.desc': 'Rigorous quality control under strict international standards, ensuring pure, safe, and highly effective formulations for your farm.',
  'rnd.pillar3.title': 'Tailored Solutions',
  'rnd.pillar3.desc': 'Bespoke nutritional and probiotic solutions customized to address specific regional challenges and precise physiological requirements.',
  'rnd.cert.title': 'Hallmarks & Certifications',
  'rnd.cert.desc': 'Space reserved for official badges and quality certifications.',
  
  'contact.title': 'Get in Touch with Confier International',
  'contact.desc': 'Contact us about anything related to our formulations, bulk pricing, or technical support. We\'ll do our best to get back to you as soon as possible.',
  'contact.hq': 'Head Office',
  'contact.call': 'Call Us',
  'contact.email': 'Email Support',
  'contact.phone': 'Phone Number',
  'contact.send': 'Send a Message',
  'contact.name': 'Your Full Name',
  'contact.email_placeholder': 'Your Email Address',
  'contact.help': 'How can we help?',
  'contact.submit': 'Submit Request',
  'contact.btn': 'SUBMIT INQUIRY',

  'auth.loginRegister': 'Login / Register',
  'auth.welcomeBack': 'Welcome Back',
  'auth.createAccount': 'Create Account',
  'auth.signInToAccount': 'Sign in to your account',
  'auth.joinConfier': 'Join us to explore Confier products',
  'auth.fullName': 'Full Name',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.signIn': 'Sign In',
  'auth.signUp': 'Sign Up',
  'auth.create': 'Create Account',
  'auth.noAccount': "Don't have an account?",
  'auth.haveAccount': 'Already have an account?',
  'auth.checkEmail': 'Check your email for verification link',
  'auth.requiredName': 'Full name is required',
  'auth.logout': 'Logout',
  'auth.signedInAs': 'Signed in as',
  'account.title': 'My Account',
  'account.subtitle': 'Track your wishlist, cart, and account details.',
  'account.welcome': 'Hi',
  'account.loggedIn': 'You are logged in',
  'account.guest': 'Please sign in to access your account and wishlist.',
  'account.wishlist': 'Wishlist Items',
  'account.cart': 'Cart Items',
  'account.emailLabel': 'Email',
  'account.roleLabel': 'Account Type',
  'account.quickActions': 'Quick Actions',
  'account.openCart': 'Open Cart',
  'account.viewProducts': 'View Products',
  'account.loginPrompt': 'Login to continue',
  'account.roleUser': 'User',
  'account.roleAdmin': 'Admin',

  'chat.title': 'Shrumpi AI',
  'chat.online': 'Online',
  'chat.thinking': 'Shrumpi is thinking...',
  'chat.listening': 'Listening...',
  'chat.input': 'Ask about pond issues, shrimp health, or product usage...',
  'chat.openProduct': 'Open Product',
  'chat.greeting': "Hello! I'm Shrumpi, your Confier product assistant. Tell me your pond, shrimp, feed, or water-quality issue and I will suggest only Confier products from this website.",
  'chat.error': 'Sorry, please try again.',
  
  'footer.company': 'Company',
  'footer.contact': 'Contact',
  'footer.privacy': 'Privacy Policy',
  'footer.terms': 'Terms',
  'footer.admin': 'Admin Login',
  'footer.desc': 'Eco-friendly shrimp feed supplements and probiotics promoting faster growth and better survival rates for sustainable farming.',
  
  'events.tag': 'Community Feed',
  'events.title': 'News & Bulletins',
  'events.desc': 'Latest field updates and technical bulletins.',
  'events.latestHeading': 'Latest updates',
  'events.adminOn': 'Admin mode on (click to turn off)',
  'events.adminOff': 'Simulate admin access',
  'events.createPost': 'Create new post',
  'events.hide': 'Hide',
  'events.expand': 'Expand',
  'events.uploadImage': 'Upload image *',
  'events.location': 'Location',
  'events.locationPh': 'e.g. Kakinada farm',
  'events.caption': 'Caption *',
  'events.captionPh': 'Write a caption…',
  'events.postCta': 'Post to feed',
  'events.deletePost': 'Delete post',
  'events.deleteComment': 'Delete comment',
  'events.likes': 'likes',
  'events.noComments': 'No comments yet. Be the first to comment!',
  'events.commentPh': 'Add a comment…',
  'events.post': 'Post',
  'events.emptyTitle': 'No posts yet',
  'events.emptyHint': 'Turn on admin mode to create the first post.',
  'events.alertNeedImage': 'Please provide an image and a caption.',
  'events.uploadImages': 'Upload photos (you can select several at once) *',
  'events.alertNeedImages': 'Add at least one photo and a caption.',
  'events.confierLive': 'Confier Live',
  'events.share': 'Share',
  'events.linkCopied': 'Link copied to clipboard.',
  'events.shareFallback': 'Share or copy the page address from your browser.',
  'events.carouselPrev': 'Previous photo',
  'events.carouselNext': 'Next photo',
  'events.photoCount': '{n} photos selected',
  'events.confirmDelete': 'Are you sure you want to delete this post?',
  'stories.quote': 'Their growth tells our success.',
  'stories.watch': 'Watch',
  'contact.alertThanks': 'Thanks for reaching out! We will contact you soon.',
  'checkout.title': 'Checkout',
  'checkout.step': 'Step {n} of 3',
  'checkout.cartTitle': 'Shopping cart ({count} items)',
  'checkout.empty': 'Your cart is empty',
  'checkout.subtotal': 'Subtotal:',
  'checkout.gst': 'GST (18%):',
  'checkout.total': 'Total:',
  'checkout.deliveryTitle': 'Delivery & contact information',
  'checkout.paymentTitle': 'Payment method',
  'checkout.orderSummary': 'Order summary',
  'checkout.items': 'Items:',
  'checkout.totalAmount': 'Total amount:',
  'checkout.close': 'Close',
  'checkout.back': 'Back',
  'checkout.continue': 'Continue',
  'checkout.review': 'Review payment',
  'checkout.placeOrder': 'Place order',
  'checkout.processing': 'Processing…',
  'checkout.field.fullName': 'Full name',
  'checkout.field.email': 'Email',
  'checkout.field.phone': 'Phone',
  'checkout.field.company': 'Company',
  'checkout.field.address': 'Address',
  'checkout.field.city': 'City',
  'checkout.field.state': 'State / province',
  'checkout.field.zip': 'Zip code',
  'checkout.field.country': 'Country',
  'checkout.pay.stripe': 'Stripe / credit card',
  'checkout.pay.razorpay': 'Razorpay (UPI / card / net banking)',
  'checkout.pay.bank': 'Bank transfer',
  'checkout.success': 'Order placed successfully! Order ID: ',
  'checkout.payFail': 'Payment failed: '
};

const teDict = {
  'nav.products': 'మా ఉత్పత్తులు',
  'nav.about': 'మా కథ',
  'nav.results': 'విజయ కథలు',
  'nav.rnd': 'ఆవిష్కరణ ప్రయోగశాల',
  'nav.updates': 'తాజా అప్‌డేట్స్',
  'nav.contact': 'మమ్మల్ని సంప్రదించండి',
  'nav.lang': 'భాష',
  'hero.badge': 'కలిసి ఎదుగుదాం',
  'hero.title1': 'కలిసి ఎదుగుదాం,',
  'hero.title2': 'కలిసి అభివృద్ధి చెందుదాం.',
  'hero.subtitle': 'భవిష్యత్తుకు ఆహారం అందించే రైతులకు ధన్యవాదాలు',
  'hero.btn1': 'మా ఉత్పత్తులను చూడండి',
  'about.tag': 'మా కథ',
  'prod.tag': 'మా ఉత్పత్తులు',
  'prod.title': 'ప్రీమియం ఫీడ్ సప్లిమెంట్స్',
  'prod.desc': 'వృద్ధి, జీవన శాతం, మరియు చెరువు ఆరోగ్యాన్ని మెరుగుపరచే శాస్త్రీయ ఫార్ములేషన్స్.',
  'rnd.tag': 'ఆవిష్కరణ ప్రయోగశాల',
  'contact.title': 'కాన్‌ఫియర్ ఇంటర్నేషనల్‌ను సంప్రదించండి',
  'contact.desc': 'మా ఉత్పత్తులు, బల్క్ ధరలు లేదా టెక్నికల్ సహాయం గురించి మమ్మల్ని సంప్రదించండి.',
  'contact.call': 'మాకు కాల్ చేయండి',
  'contact.phone': 'ఫోన్ నంబర్',
  'contact.name': 'మీ పూర్తి పేరు',
  'contact.help': 'మేము ఎలా సహాయం చేయగలం?',
  'contact.btn': 'విచారణ పంపండి',
  'auth.loginRegister': 'లాగిన్ / నమోదు',
  'auth.welcomeBack': 'మళ్లీ స్వాగతం',
  'auth.createAccount': 'ఖాతా సృష్టించండి',
  'auth.signInToAccount': 'మీ ఖాతాలోకి లాగిన్ అవ్వండి',
  'auth.joinConfier': 'కాన్‌ఫియర్ ఉత్పత్తులను చూడటానికి చేరండి',
  'auth.fullName': 'పూర్తి పేరు',
  'auth.email': 'ఈమెయిల్',
  'auth.password': 'పాస్‌వర్డ్',
  'auth.signIn': 'లాగిన్ అవ్వండి',
  'auth.signUp': 'సైన్ అప్',
  'auth.create': 'ఖాతా సృష్టించండి',
  'auth.noAccount': 'ఖాతా లేదా?',
  'auth.haveAccount': 'ఇప్పటికే ఖాతా ఉందా?',
  'auth.checkEmail': 'వెరిఫికేషన్ లింక్ కోసం మీ ఈమెయిల్ చూడండి',
  'auth.requiredName': 'పూర్తి పేరు అవసరం',
  'auth.logout': 'లాగౌట్',
  'auth.signedInAs': 'లాగిన్ అయిన వినియోగదారు',
  'account.title': 'నా ఖాతా',
  'account.subtitle': 'మీ విష్‌లిస్టు, కార్ట్ మరియు ఖాతా వివరాలను చూడండి.',
  'account.welcome': 'హాయ్',
  'account.loggedIn': 'మీరు లాగిన్ అయ్యారు',
  'account.guest': 'మీ ఖాతా మరియు విష్‌లిస్టు కోసం దయచేసి లాగిన్ అవ్వండి.',
  'account.wishlist': 'విష్‌లిస్టు అంశాలు',
  'account.cart': 'కార్ట్ అంశాలు',
  'account.emailLabel': 'ఈమెయిల్',
  'account.roleLabel': 'ఖాతా రకం',
  'account.quickActions': 'త్వరిత చర్యలు',
  'account.openCart': 'కార్ట్ తెరవండి',
  'account.viewProducts': 'ఉత్పత్తులు చూడండి',
  'account.loginPrompt': 'కొనసాగడానికి లాగిన్ అవ్వండి',
  'account.roleUser': 'వినియోగదారు',
  'account.roleAdmin': 'అడ్మిన్',
  'chat.title': 'శ్రుంపి AI',
  'chat.online': 'ఆన్‌లైన్',
  'chat.thinking': 'శ్రుంపి ఆలోచిస్తోంది...',
  'chat.listening': 'వింటోంది...',
  'chat.input': 'చెరువు, శ్రిమ్ప్ ఆరోగ్యం, లేదా ఉత్పత్తి వినియోగం గురించి అడగండి...',
  'chat.openProduct': 'ఉత్పత్తి తెరవండి',
  'chat.greeting': 'నమస్కారం! నేను శ్రుంపి. మీ చెరువు, శ్రిమ్ప్, ఫీడ్ లేదా నీటి సమస్య చెప్పండి. ఈ వెబ్‌సైట్‌లో ఉన్న కాన్‌ఫియర్ ఉత్పత్తులనే నేను సూచిస్తాను.',
  'chat.error': 'క్షమించండి, దయచేసి మళ్లీ ప్రయత్నించండి.'
};

const hiDict = {
  'nav.products': 'हमारे उत्पाद',
  'nav.about': 'हमारी कहानी',
  'nav.results': 'सफलता की कहानियाँ',
  'nav.rnd': 'इनोवेशन लैब',
  'nav.updates': 'नवीनतम अपडेट',
  'nav.contact': 'संपर्क करें',
  'nav.lang': 'भाषा',
  'hero.badge': 'साथ मिलकर बढ़ते हैं',
  'hero.title1': 'साथ मिलकर बढ़ें,',
  'hero.title2': 'साथ मिलकर आगे बढ़ें।',
  'hero.subtitle': 'भविष्य को पोषण देने वाले किसानों को धन्यवाद',
  'hero.btn1': 'हमारे उत्पाद देखें',
  'about.tag': 'हमारी कहानी',
  'prod.tag': 'हमारे उत्पाद',
  'prod.title': 'प्रीमियम फीड सप्लीमेंट्स',
  'prod.desc': 'विकास, सर्वाइवल और तालाब स्वास्थ्य सुधारने के लिए वैज्ञानिक फॉर्मूलेशन।',
  'rnd.tag': 'इनोवेशन लैब',
  'contact.title': 'कॉनफियर इंटरनेशनल से संपर्क करें',
  'contact.desc': 'हमारे उत्पादों, थोक मूल्य या तकनीकी सहायता के बारे में हमसे संपर्क करें।',
  'contact.call': 'हमें कॉल करें',
  'contact.phone': 'फोन नंबर',
  'contact.name': 'आपका पूरा नाम',
  'contact.help': 'हम आपकी कैसे मदद कर सकते हैं?',
  'contact.btn': 'पूछताछ भेजें',
  'auth.loginRegister': 'लॉगिन / रजिस्टर',
  'auth.welcomeBack': 'फिर से स्वागत है',
  'auth.createAccount': 'खाता बनाएँ',
  'auth.signInToAccount': 'अपने खाते में साइन इन करें',
  'auth.joinConfier': 'कॉनफियर उत्पाद देखने के लिए जुड़ें',
  'auth.fullName': 'पूरा नाम',
  'auth.email': 'ईमेल',
  'auth.password': 'पासवर्ड',
  'auth.signIn': 'साइन इन',
  'auth.signUp': 'साइन अप',
  'auth.create': 'खाता बनाएँ',
  'auth.noAccount': 'क्या आपका खाता नहीं है?',
  'auth.haveAccount': 'क्या आपके पास पहले से खाता है?',
  'auth.checkEmail': 'वेरिफिकेशन लिंक के लिए अपना ईमेल देखें',
  'auth.requiredName': 'पूरा नाम आवश्यक है',
  'auth.logout': 'लॉगआउट',
  'auth.signedInAs': 'साइन इन उपयोगकर्ता',
  'account.title': 'मेरा खाता',
  'account.subtitle': 'अपनी विशलिस्ट, कार्ट और खाते का विवरण देखें।',
  'account.welcome': 'नमस्ते',
  'account.loggedIn': 'आप लॉगिन हैं',
  'account.guest': 'अपना खाता और विशलिस्ट देखने के लिए कृपया लॉगिन करें।',
  'account.wishlist': 'विशलिस्ट आइटम',
  'account.cart': 'कार्ट आइटम',
  'account.emailLabel': 'ईमेल',
  'account.roleLabel': 'खाता प्रकार',
  'account.quickActions': 'त्वरित कार्य',
  'account.openCart': 'कार्ट खोलें',
  'account.viewProducts': 'उत्पाद देखें',
  'account.loginPrompt': 'जारी रखने के लिए लॉगिन करें',
  'account.roleUser': 'उपयोगकर्ता',
  'account.roleAdmin': 'एडमिन',
  'chat.title': 'श्रुंपी AI',
  'chat.online': 'ऑनलाइन',
  'chat.thinking': 'श्रुंपी सोच रही है...',
  'chat.listening': 'सुन रही है...',
  'chat.input': 'तालाब, झींगा स्वास्थ्य या उत्पाद उपयोग के बारे में पूछें...',
  'chat.openProduct': 'उत्पाद खोलें',
  'chat.greeting': 'नमस्ते! मैं श्रुंपी हूँ। अपने तालाब, झींगा, फीड या पानी की समस्या बताइए। मैं केवल इसी वेबसाइट के कॉनफियर उत्पाद सुझाऊँगी।',
  'chat.error': 'माफ़ कीजिए, कृपया फिर से प्रयास करें।'
};

const teBundle = { ...enDict, ...teDict, ...teExtras };
const hiBundle = { ...enDict, ...hiDict, ...hiExtras };
const englishFallback = { ...enDict };

const dictionaries = Object.fromEntries(
  SUPPORTED_LANG_CODES.map((code) => {
    if (code === 'en') return [code, enDict];
    if (code === 'te') return [code, teBundle];
    if (code === 'hi') return [code, hiBundle];
    return [code, englishFallback];
  })
);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState('en');

  const setLang = useCallback((code) => {
    const next = typeof code === 'string' && dictionaries[code] ? code : 'en';
    setLangState(next);
  }, []);

  const dict = useMemo(() => dictionaries[lang] || enDict, [lang]);
  const t = useCallback((key) => dict[key] || enDict[key] || key, [dict]);

  useEffect(() => {
    if (typeof document === 'undefined') return;
    const htmlLang =
      lang === 'zh' ? 'zh-Hans' : lang === 'ar' ? 'ar' : lang === 'pt' ? 'pt' : lang;
    document.documentElement.lang = htmlLang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
